[theme]
base = "dark"
primaryColor = "#ff6f61"  # 鮮やかなサーモンピンク
backgroundColor = "#2e2e2e"  # ダークグレーの背景色
secondaryBackgroundColor = "#383838"  # サイドバーの背景色
textColor = "#ffffff"  # ホワイト
font = "monospace"  # モノスペースフォントで個性を演出

[server]
headless = true
enableCORS = false

[global]
minBrowser = "chrome:70"

# 追加のカスタムCSSを設定
[theme.custom_css]
css = """
/* 全体のフォントとボーダーを設定 */
body {
    font-family: 'Courier New', monospace;
    color: #ffffff;
}

/* 入力フィールドのスタイルを設定 */
input[type="text"] {
    background-color: #3c3c3c;
    color: #ffffff;
    padding: 12px;
    border: 2px solid #ff6f61;
    border-radius: 8px;
    box-shadow: 0 0 15px rgba(255, 111, 97, 0.4);
}

/* ボタンのスタイルを設定 */
button {
    background-color: #ff6f61;
    color: white;
    padding: 12px 25px;
    border: none;
    border-radius: 8px;
    box-shadow: 0 0 15px rgba(255, 111, 97, 0.6);
    transition: background-color 0.3s ease, box-shadow 0.3s ease;
}

button:hover {
    background-color: #ff5349;
    box-shadow: 0 0 20px rgba(255, 83, 73, 0.8);
}

/* サイドバーのスタイルを設定 */
.sidebar .stMarkdown {
    background-color: #3c3c3c;
    color: #ffffff;
    border: 2px solid #ff6f61;
    border-radius: 8px;
    padding: 20px;
    box-shadow: 0 0 15px rgba(255, 111, 97, 0.4);
}

/* ヘッダーとリンクのスタイルを設定 */
h3, h1, h2, a {
    color: #ff6f61;
    text-shadow: 1px 1px 2px rgba(255, 111, 97, 0.7);
}

/* プログレスバーのスタイルを設定 */
.stProgress > div > div {
    background-color: #ff6f61;
    box-shadow: 0 0 15px rgba(255, 111, 97, 0.6);
}

/* カスタムスクロールバー */
::-webkit-scrollbar {
    width: 12px;
}

::-webkit-scrollbar-track {
    background: #3c3c3c;
}

::-webkit-scrollbar-thumb {
    background-color: #ff6f61;
    border-radius: 6px;
    border: 3px solid #3c3c3c;
}
"""
