[theme]
base = "dark"
primaryColor = "#f50057"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#292929"
textColor = "#e0e0e0"
font = "monospace"

[server]
headless = true
enableCORS = false

[global]
minBrowser = "chrome:70"
